<?php

namespace BG\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use BG\PlateformBundle\Entity\Client;
use Doctrine\ORM\QueryBuilder;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function myGetClient()
  	{
	    $qb = $this->createQueryBuilder('a');
	    $qb
	      ->join("a.Client","c")
	      ->addSelect("c")
	      ;
	    return $qb
	      ->getQuery()
	      ->getResult()
	    ;
  	}
}
