<?php

namespace BG\PlateformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
	public function getClientWithUser($id){
		$qb = $this->createQueryBuilder('c');
	    $qb
	    	->join("c.User","u","WITH","u.id = :id")
	    	->setParameter('id',$id)
	    	->addSelect("u")
	      ;
	    return $qb
	      ->getQuery()
	      ->getResult()
	    ;
	}
}
