<?php

namespace BG\PlateformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OportunityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OportunityRepository extends EntityRepository
{
}
